name: audio_io_example
description: Demonstrates how to use the audio_io plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  audio_io:
    path: ../

flutter:

  uses-material-design: true